name: Deploy Franz Project

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Stop old container if exists
        run: docker stop franz_8081 || true && docker rm franz_8081 || true

      - name: Build new Docker image
        run: docker build -t franz_image_8081 .

      - name: Run new container on port 8081
        run: docker run -d --name franz_8081 -p 8081:80 franz_image_8081
